## Part 1: Preprocessing

In [107]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.layers import Input, Dense

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [108]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [109]:
# Create y_df with the Attrition and Department columns

y_df = attrition_df[['Attrition', 'Department']]

In [110]:

# Create a list of at least 10 column names to use as X data
X_col = ['DistanceFromHome','EnvironmentSatisfaction','HourlyRate','JobInvolvement','JobSatisfaction','NumCompaniesWorked','PerformanceRating','StockOptionLevel','WorkLifeBalance','YearsAtCompany']

# Create X_df using your selected columns
X_df = attrition_df[X_col]

# Show the data types for X_df
X_df.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   DistanceFromHome         1470 non-null   int64
 1   EnvironmentSatisfaction  1470 non-null   int64
 2   HourlyRate               1470 non-null   int64
 3   JobInvolvement           1470 non-null   int64
 4   JobSatisfaction          1470 non-null   int64
 5   NumCompaniesWorked       1470 non-null   int64
 6   PerformanceRating        1470 non-null   int64
 7   StockOptionLevel         1470 non-null   int64
 8   WorkLifeBalance          1470 non-null   int64
 9   YearsAtCompany           1470 non-null   int64
dtypes: int64(10)
memory usage: 115.0 KB


In [111]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=13)

In [112]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

# Converting features from integer to float
X_df = X_df.astype('float32')

# Check data types
X_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   DistanceFromHome         1470 non-null   float32
 1   EnvironmentSatisfaction  1470 non-null   float32
 2   HourlyRate               1470 non-null   float32
 3   JobInvolvement           1470 non-null   float32
 4   JobSatisfaction          1470 non-null   float32
 5   NumCompaniesWorked       1470 non-null   float32
 6   PerformanceRating        1470 non-null   float32
 7   StockOptionLevel         1470 non-null   float32
 8   WorkLifeBalance          1470 non-null   float32
 9   YearsAtCompany           1470 non-null   float32
dtypes: float32(10)
memory usage: 57.5 KB


In [113]:
# Create a StandardScaler
X_scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [114]:
# Create a OneHotEncoder for the Department column
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder to the training data
department_train = y_train[['Department']]
department_test = y_test[['Department']]

ohe.fit(department_train)

# Create two new variables by applying the encoder
# to the training and testing data
department_train_encoded = ohe.transform(department_train)
department_test_encoded = ohe.transform(department_test)

print(department_train_encoded.shape)
print(department_test_encoded.shape)

print(department_train_encoded)
print(department_test_encoded)

(1102, 3)
(368, 3)
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [115]:
# Initialize the OneHotEncoder
onehot_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder on the training data
onehot_encoder.fit(y_train[['Department']])

# Transform both training and testing data
y_train_department_encoded = onehot_encoder.transform(y_train[['Department']])
y_test_department_encoded = onehot_encoder.transform(y_test[['Department']])

# Verify the shapes
print("y_train_department_encoded shape:", y_train_department_encoded.shape)
print("y_test_department_encoded shape:", y_test_department_encoded.shape)



y_train_department_encoded shape: (1102, 3)
y_test_department_encoded shape: (368, 3)


In [116]:
# Create a OneHotEncoder for the Attrition column
ohe = OneHotEncoder(sparse_output=False, drop='if_binary')

# Fit the encoder to the training data
attrition_train = y_train[['Attrition']]
attrition_test = y_test[['Attrition']]

ohe.fit(y_df[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
attrition_train_encoded = ohe.transform(attrition_train)
attrition_test_encoded = ohe.transform(attrition_test)

print(attrition_train_encoded)
print(attrition_test_encoded)

[[0.]
 [1.]
 [1.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

## Create, Compile, and Train the Model

In [118]:
# Find the number of columns in the X training data
features = X_train.shape[1]

# Create the input layer
input_layer = Input(shape=(features,), name='input_layer')

# Create at least two shared layers
shared_layer1 = Dense(16, activation='relu', name='shared_layer1')(input_layer)
shared_layer2 = Dense(32, activation='relu', name='shared_layer2')(shared_layer1)

In [119]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dept_hidden_layer = Dense(16, activation='relu', name='dept_hidden_layer')(shared_layer2)


# Create the output layer
dept_output = Dense(3, activation='softmax', name='department_output')(dept_hidden_layer)


In [120]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden_layer = Dense(16, activation='relu', name='attrition_hidden_layer')(shared_layer2)

# Create the output layer
attrition_output = Dense(1, activation='sigmoid', name='attrition_output')(attrition_hidden_layer)


In [121]:
# Create the model

model = Model(
    inputs={'input_layer': input_layer},
    outputs={
        'department_output': dept_output,
        'attrition_output': attrition_output
    }
)
model.compile(
    optimizer='adam',
    loss={
        'department_output': 'categorical_crossentropy',  # For one-hot encoded labels
        'attrition_output': 'binary_crossentropy'         # For binary labels
    },
    metrics={
        'department_output': 'accuracy',
        'attrition_output': 'accuracy'
    }
)
# Summarize the model
model.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 10)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared_layer1       │ (None, 16)        │        176 │ input_layer[0][0] │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared_layer2       │ (None, 32)        │        544 │ shared_layer1[0]… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden_l… │ (None, 16)        │        528 │ shared_layer2[0]… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dept_hidden_layer   │ (None, 16)        │        528 │ shared_layer2[0]… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 1)         │         17 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output   │ (None, 3)         │         51 │ dept_hidden_laye… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,844 (7.20 KB)

 Trainable params: 1,844 (7.20 KB)

 Non-trainable params: 0 (0.00 B)

In [122]:
history = model.fit(
    X_train,
    {
        'department_output': y_train_department_encoded,  
        'attrition_output': y_train_attrition             
    },
    validation_data=(
        X_test,
        {
            'department_output': y_test_department_encoded,
            'attrition_output': y_test_attrition
        }
    ),
    epochs=10,
    batch_size=32
)

Epoch 1/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - attrition_output_accuracy: 0.5025 - attrition_output_loss: 1.7533 - department_output_accuracy: 0.5936 - department_output_loss: 2.7668 - loss: 4.5210 - val_attrition_output_accuracy: 0.8288 - val_attrition_output_loss: 0.5427 - val_department_output_accuracy: 0.5109 - val_department_output_loss: 0.8858 - val_loss: 1.4185
Epoch 2/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.7977 - attrition_output_loss: 0.6296 - department_output_accuracy: 0.5591 - department_output_loss: 0.9225 - loss: 1.5526 - val_attrition_output_accuracy: 0.8179 - val_attrition_output_loss: 0.5029 - val_department_output_accuracy: 0.6168 - val_department_output_loss: 0.7576 - val_loss: 1.2477
Epoch 3/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8234 - attrition_output_loss: 0.5369 - department_output_accuracy: 0.6025 - department_output_loss: 0.8804 - loss: 1.4168 - val_attrition_output_accuracy: 0.8424 - val

In [123]:
# Evaluate the model with the testing data
evaluation = model.evaluate(X_test, {'attrition_output': y_test_attrition, 'department_output': y_test_department_encoded})

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8463 - attrition_output_loss: 0.4081 - department_output_accuracy: 0.6808 - department_output_loss: 0.6929 - loss: 1.0989 


In [125]:
# Print the accuracy for both department and attrition
print(f"Attrition Accuracy: {evaluation[3]}")   
print(f"Department Accuracy: {evaluation[4]}")  



Attrition Accuracy: 0.842391312122345
Department Accuracy: 0.66847825050354


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Attrition data is imbalanced, the classification report should be used in place of accuracy. 
2. Softmax is best for the department output because department has three possible values; while sigmoid is best for attrition due to it's ability to work with binary numbers.
3. Analised and tried different features to see is they impact the models. And finetuning models with different nubmers of neurons and layers. 